### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by homerjam** [krestaino/nuepress#33]
Hi @krestaino

I'm wondering if you could help with some high level questions about this WP + Nuxt approach. As somebody who generally avoids WP I'm trying to gain some insight and figure out the viability for a new project...

What, if any, are the limitations/differences for both developer and site admin?

eg. there is an 'admin bar' available to normal WP themes I believe - is this available? If not what functionality is lost?

Is it possible to preview content? I'd assume this would require being authenticated were it a normal theme - is this replicable? Perhaps using https://github.com/Tmeister/wp-api-jwt-auth

Are there problems with any commonly used plugins? Caching, custom fields etc.

Are there any other obvious caveats/hurdles that spring to mind?

Many thanks in advance!
James

**Comment by krestaino** [comment]
Hello!

As of now, NuePress is only using publicly available endpoints. So anything requiring authentication (like you mentioned, previews) is not yet supported. I think that's a very important feature and should be added to NuePress. https://github.com/Tmeister/wp-api-jwt-auth looks great, I'm defintely going to look into that, thanks.

The biggest limitations being a site admin would be the lack of control within the WordPress admin. You can't edit menu's, nothing under Appearance will do anything, several settings won't do anything (such as changing link structure). All of those things are handled within NuePress.

Originally my goal with this project was to completely decouple the front-end from the back-end and rely on a brand new WordPress install with no additional configuration. So for plugin support, I honestly haven't tried any so far. However, if the plugin exposes data in the Rest API, I don't see why NuePress couldn't consume that data.

Caching is an issue. There's a great plugin that I used for a bit until I ran into a bug. Several people seem to be affected by it, you can see that here. https://github.com/airesvsg/wp-rest-api-cache/issues/9 It's a shame, because that plugin really improved the response times from the API. However, NuePress in it's current state is still pretty snappy. I'm unaware of any other solutions out there that cache the API calls.

Hope that helps a bit!

Also, if you have any suggestions or see ways to help or improve the current project, PR's are more than welcome!

**Comment by homerjam** [comment]
Thanks, yes that helps a lot!

I'm not too concerned about the appearance side of things - editing menus could be useful though. Previews and caching are dealbreakers.

How do previews work? Is it as simple as making an authenticated request?

A possible caching solution would be a proxy running alongside Nuxt - it'd be simplistic (basically caching all API requests indeterminately) but do the job.

This [WPGraphql](https://github.com/wp-graphql/wp-graphql) project looks interesting and could be a good addition, possibly combined with Apollo.

**Comment by krestaino** [comment]
> How do previews work? Is it as simple as making an authenticated request?

Honestly, I'm not sure as I haven't looked into it just yet. It's definitely something I want to add.

>A possible caching solution would be a proxy running alongside Nuxt - it'd be simplistic (basically caching all API requests indeterminately) but do the job.

Thanks for this suggestion I found this [guide ](https://bneijt.nl/blog/post/setting-up-nginx-caching-for-api-use/) to cache the API calls and I'm seeing a dramatic improvement in response times. A few larger API calls used to be upwards of 500-600ms. With the caching proxy those calls are going down to < 50ms.

>This WPGraphql project looks interesting and could be a good addition, possibly combined with Apollo.

I would love to eventually use WPGraphql, but I don't think it's ready just yet. The docs are lacking and I've encountered a few bugs just playing around with it.
