### ISSUE TITLE
Feasible to make this into a WP theme?

### ISSUE THREAD

**Issue by msacchetti** [krestaino/nuepress#41]
Hi, i've been using Vue within WordPress themes, mainly because the clients have needed all the WP Admin features (menus etc) so I haven't fully decoupled the front and back end, and found this to be a good workflow.

I am not experienced with Nuxt but really want to use this starter for my next project, so i'm wondering if you think there would be huge hurdles if I tried to make this a WP theme? I assume I'd plan to leave all the routing in nuepress and make a custom menu walker to handle the nav menu integration.

If you think it could make sense as WP theme, i will take a stab at it and share! 

Any insights appreciated, great work on this.

**Comment by krestaino** [comment]
Hello!

Do you mean selecting the theme from within the WordPress admin? If so, I'm not sure how that could work. WordPress themes are built in PHP, Nuxt is basically just a Node app and it isn't concerned at all with the back-end WordPress API. All NuePress consumes is JSON. In fact, you should be able to easily swap out the WordPress back-end with another CMS.

For menus/nav, there's this [plugin](https://wordpress.org/plugins/wp-api-menus/) which exposes an endpoint so you can potentially use the menu builder within WordPress to populate the NuePress nav. I haven't tested it, but it should be pretty straightforward.

You should check out this [issue](https://github.com/krestaino/nuepress/issues/33), there may be some helpful info in there. There's some concerns I have using NuePress as a site admin, rather than the site dev, that I address in that issue.

Sorry if I didn't fully address your question, but let me know if you have anymore questions and I'll do my best to answer them.

**Comment by msacchetti** [comment]
Thanks for the help. I guess my question was not so clear now that i re-read it.

I've taken a pure Vue app and converted it to a WordPress theme pretty easily by doing the bare minimum requirements for a theme: add a functions.php, style.css file etc. The app still is mostly decoupled from the backend and gets all the data via the WP API, but having it as an installable theme allows me to use native WP PHP functionality here and there when needed.

I was thinking if I am able to put nuxt into [mode: 'spa'] to eliminate server side rendering, it would be possible to do the same. 

I am going to take a stab at this today and will report back with any insights.
